export default {
  getCartItems: (state) => state.cart,
  getCartObjects: (state) => state.cart_objects,
  getCheckoutCustomer: (state) => state.checkout_customer,
  getCustomers: (state) => state.customers,
  getEmail: (state) => state.unregistered_email,
  getEmailStatus: (state) => state.email_verified,
  getFilterOption: (state) => state.filter_option,
  getHasCustomer: (state) => state.has_customer,
  getHasProduct: (state) => state.has_product,
  getHasSale: (state) => state.has_sale,
  getMetrics: (state) => state.metrics,
  getComponentSettings: (state) => state.component_settings,
  getInventory: (state) => state.inventory,
  getLoggedIn: (state) => state.logged_in,
  getOrders: (state) => state.orders,
  getProductToBeEditted: (state) => state.to_be_editted,
  getSettingsState: (state) => state.settings,
  getSettlement: (state) => state.settlement,
  getState: (state) => state,
  getStore: (state) => state.store,
  getStoreSlug: (state) => state.store_slug,
  getUnsavedChange: (state) => state.unsaved_change,
}